theme = "diary"
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3


[[menu.main]]
url = "https://www.linkedin.com/in/jeffreyellin/"
name = "LinkedIn"
weight = 99

[[menu.main]]
url = "http://github.com/jeffellin"
name = "GitHub"
weight = 100

title = "A Hugo Site"
copyright = "This is a customized copyright."

baseURL = "/sd"
[params]
subtitle = "Not so Interesting Blog"
title = "Application Modernization Cookbook"

enableGitalk = false


[permalinks]
  posts = "/:year/:month/:day/:title/"
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6